# This is a basic workflow to help you get started with Actions

name: Auto Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4     
      
      - name: run script
        shell: powershell
        run: |
          cd BuildPackages
          powershell .\update-zip.ps1

      #https://stackoverflow.com/questions/64868918/how-to-download-artifact-release-asset-in-another-workflow
      #- uses: actions/download-artifact@v4
      #  with:
      #    name: php.zip
      #    github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
      #    repository: lsq/lanzouyunapi
      #    run-id: 10398898260
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, curl, apcu
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit
          
      - name: pack php installed files
        shell: powershell
        run: |
          $tf = ".\php-8.3-nts-x64.zip"
          if (Test-Path $tf) { Remove-Item -Path $tf  -Force -ErrorAction SilentlyContinue}
          7z a -mx9 $tf c:\tools\php

      - uses: int128/update-generated-files-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  
